name: bennettprojectgallery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_fonts: ^2.1.1
  responsive_builder: ^0.2.0+2
  change_app_package_name: ^1.0.0
  animated_text_kit: ^4.2.1
  countup: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: Montserrat-Extralight
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf

    - family: Montserrat-Medium
      fonts:    
        - asset: fonts/Montserrat-Medium.ttf

    - family: Metrisch-Bold
      fonts:
        - asset: fonts/Metrisch-Bold.otf

    - family: Metrisch-Medium
      fonts:
        - asset: fonts/Metrisch-Medium.otf
    - family: Metrisch-ExtraBold
      fonts:
        - asset: fonts/Metrisch-ExtraBold.otf
